force-app/main/default/objects/CountryLayer__c/CountryLayer__c.object-meta.xml
<CustomObject>
    <label>Country</label>
    <nameField>
        <label>Country</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CountryLayers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CountryLayer__c/fields/Capital_City__c.field-meta.xml
<CustomField>
    <fullName>Capital_City__c</fullName>
    <label>Capital City</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CountryLayer__c/fields/Country_ISO_Code_2__c.field-meta.xml
<CustomField>
    <fullName>Country_ISO_Code_2__c</fullName>
    <label>Country ISO Code 2</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CountryLayer__c/fields/Country_ISO_Code_3__c.field-meta.xml
<CustomField>
    <fullName>Country_ISO_Code_3__c</fullName>
    <label>Country ISO Code 3</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CountryLayer__c/fields/Subregion__c.field-meta.xml
<CustomField>
    <fullName>Subregion__c</fullName>
    <label>Subregion</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CountryLayerAPITest.cls
@isTest
public class CountryLayerAPITest {
    @TestSetup
    static void makeData(){
        CountryLayer__c cl = new CountryLayer__c();
        cl.Name='Palestine';
        cl.Country_ISO_Code_2__c='PAS';
        cl.Country_ISO_Code_3__c='PA';
        cl.Capital_City__c='Jerusalam';
        cl.Region__c='Middle East';
        cl.Subregion__c='';
        insert cl;

        Regional_Bloc__c rb = new Regional_Bloc__c(Name='OIC', CountryLayer__c=cl.Id);
        insert rb;
    }
    @IsTest
    static void methodName(){
        Test.startTest();
        Test.setMock(HttpCalloutMock.Class, new MockHttpResponseGenerator());
        CountryLayerAPI.callCountryLayerService();
        Test.stopTest();
    }
}