force-app/main/default/objects/CountryLayer__c/CountryLayer__c.object-meta.xml
<CustomObject>
    <label>Country</label>
    <nameField>
        <label>Country</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CountryLayers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CountryLayer__c/fields/Capital_City__c.field-meta.xml
<CustomField>
    <fullName>Capital_City__c</fullName>
    <label>Capital City</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CountryLayer__c/fields/Country_ISO_Code_2__c.field-meta.xml
<CustomField>
    <fullName>Country_ISO_Code_2__c</fullName>
    <label>Country ISO Code 2</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CountryLayer__c/fields/Country_ISO_Code_3__c.field-meta.xml
<CustomField>
    <fullName>Country_ISO_Code_3__c</fullName>
    <label>Country ISO Code 3</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CountryLayer__c/fields/Subregion__c.field-meta.xml
<CustomField>
    <fullName>Subregion__c</fullName>
    <label>Subregion</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Capital_City_Text__c.field-meta.xml
<CustomField>
    <fullName>Capital_City_Text__c</fullName>
    <label>Capital City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Country_ISO_Code_2_Text__c.field-meta.xml
<CustomField>
    <fullName>Country_ISO_Code_2_Text__c</fullName>
    <label>Country ISO Code 2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Country_ISO_Code_3_Text__c.field-meta.xml
<CustomField>
    <fullName>Country_ISO_Code_3_Text__c</fullName>
    <label>Country ISO Code 3</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/CountryLayer__c.field-meta.xml
<CustomField>
    <fullName>CountryLayer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Country</label>
    <referenceTo>CountryLayer__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <formula>CountryLayer__r.Region__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Region</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Subregion__c.field-meta.xml
<CustomField>
    <fullName>Subregion__c</fullName>
    <formula>CountryLayer__r.Subregion__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Subregion</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CountryLayerTriggerHandler.cls
/******************************************************************************************
  @description       : Lead Trigger Handler Class
  @author            : Mohammad Anzar
  @test class        : CountryLayerAPITest 
  @last modified on  : 06-03-2023
  @last modified by  : Mohammad Anzar
  Modifications Log
  Ver   Date         Author           Modification       Method
  1.0   06-03-2023   Mohammad Anzar   Initial Version    updateCountryDetailsOnLead
*******************************************************************************************/
public class CountryLayerTriggerHandler {
    //update related lead when any change happens in certain fields of Country
    public static void updateCountryDetailsOnLead(List<CountryLayer__c> clLst, Map<Id, CountryLayer__c> newMap) {
        List<Lead> toUpdateLeadLst = new List<Lead>();
        for(Lead ld : [Select Id, CountryLayer__c, Region_Text__c, Subregion_Text__c, Country_ISO_Code_2_Text__c, Country_ISO_Code_3_Text__c, Capital_City_Text__c From Lead Where CountryLayer__c IN : clLst]){
            CountryLayer__c cl = newMap.get(ld.CountryLayer__c);
            if(cl.Region__c <> ld.Region_Text__c)
                ld.Region_Text__c = cl.Region__c;
            if(cl.Subregion__c <> ld.Subregion_Text__c)
                ld.Subregion_Text__c = cl.Subregion__c;
            if(cl.Country_ISO_Code_2__c <> ld.Country_ISO_Code_2_Text__c)
                ld.Country_ISO_Code_2_Text__c = cl.Country_ISO_Code_2__c;
            if(cl.Country_ISO_Code_3__c <> ld.Country_ISO_Code_3_Text__c)
                ld.Country_ISO_Code_3_Text__c = cl.Country_ISO_Code_3__c;
            if(cl.Capital_City__c <> ld.Capital_City_Text__c)
                ld.Capital_City_Text__c = cl.Capital_City__c;
            toUpdateLeadLst.add(ld);
        }
        if(!toUpdateLeadLst.isEmpty())
            update toUpdateLeadLst;
    }
}